### ISSUE TITLE
Error responses with code 504 are not being retried

### ISSUE THREAD

**Issue by ea-mtenhoor** [Ed-Fi-Exchange-OSS/API-Publisher#3]
When running the API Publisher with `--includeDescriptors=true`, not all of the descriptors are making it across.  Some do, and if the publisher is run again a few more descriptors might make it.  It appears that the target server is getting overwhelmed and the nginx proxy on the target system starts responding with "504 Gateway Timeout".  It seems that when this error occurs, the retry logic doesn't happen.
For example, if I filter the logs for just events with "gradeLevelDescriptors" in the message, I do see one message about retries ("Retrying resource (attempt #1 of 5 failed with status 'InternalServerError')") but there is never an attempt 2.  All the other errors are about the gateway time out.
```
67549 [10] ERROR EdFi.Tools.ApiPublisher.Core.Processing.Blocks.PostResource (null) - data/v3/ed-fi/gradeLevelDescriptors (source id: cb54a292205642d2915dc09050e1b38e): POST returned GatewayTimeout
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```
Then, the ChangeProcessor says "Streaming of '/ed-fi/gradeLevelDescriptors' completed. 179 resource(s) remaining."  Comparing the contents of both ODS's directly shows that only some of the gradeLevelDescriptors were successfully published.  The desired behavior would be for the API Publisher to perform exponential backoff when presented with a 504 response, and retry until success or `--maxRetryAttempts` is exceeded.

**Comment by gmcelhanon** [comment]
Issue was resolved.
